[package]
name = "rest_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
actix-cors = "0.6.3"
actix-rt = "2.7.0"
actix-web-httpauth = "0.8.0"

reqwest = "0.11.12"
mongodb = "2.3.1"
futures = "0.3.25"
serde = "1.0.147"
dotenv = "0.15.0"